### ISSUE TITLE
#import "sqlite3.h" in JPSimulatorHacksDB.h causes build failure in swift

### ISSUE THREAD

**Issue by dbenninger** [plu/JPSimulatorHacks#5]
When I added the JPSimulatorHacks pod to my swift project and added the #import <JPSimulatorHacks/JPSimulatorHacks.h> line to my bridging header, building failed with the error message:

(...)/Pods/JPSimulatorHacks/JPSimulatorHacks/JPSimulatorHacksDB.h:28:9: Include of non-modular header inside framework module 'JPSimulatorHacks.JPSimulatorHacksDB'

Looking on stackoverflow, I found the following http://stackoverflow.com/a/24728646/5215824 and moved #import "sqlite3.h" from JPSimulatorHacksDB.h to JPSimulatorHacksDB.m. That solved the issue and the library works like a charm...

Is there any need for the sqlite import in the public header file?

**Comment by plu** [comment]
You're right - there's no reason to have it in the header. I'll move it as you suggested and make a new tag/release!

**Comment by dbenninger** [comment]
great, thanks!
